nginx:
  build: .
  restart: always
  ports:
    - 81:81
    - 82:82
    - 83:83
  volumes:
    - $PWD/container/nginx.conf:/etc/nginx/nginx.conf
    - $PWD/api:/www/api
    - $PWD/app/www:/www/app/www
    - $PWD/backend:/www/backend
    - $PWD/api/dbdumps/piox_dbdump_20170403_1006_piox_after_game.sql:/www/dbdump.sql
  links:
    - mysql

mysql:
  image: mysql:5.7
  restart: always
  ports:
    - 127.0.0.1:3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: mysecretpioXdbpassword
