prometheus:
  image: prom/prometheus
  ports:
    - "127.0.0.1:9090:9090"
  volumes:
    - ./config:/etc/prometheus
    - ./data:/prometheus

grafana:
  image: grafana/grafana
  ports:
    - 127.0.0.1:3000:3000
  links:
    - prometheus
  environment:
    GRAFANA_USER: admin
    GRAFANA_PASS: piox
